version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - dev
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - dev   
networks:
    dev:
      driver: bridge