apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYmFqS2NZb1FhYlV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBek1UVXhNakV6TlROYUZ3MHpOVEF6TVRNeE1qRTROVE5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNzc0EwVFlrRVpzY1hORk93RlVYRm1LZHhmY3NwLytraWNPcnlpUGNBcHBNanZFaTd0bFVUS012OUIKTUVXUWV2Y2tCclFNdC85Z2JkdTdBVkRGOFZVcHlDS1AvalQ0bVk0R2NxQ0FaR0JrOVlsQ21IQ3lROGNwanlIMAo5SzVsME9obmQvUnVtM09uMGlyZVdubENrTkdUcWhLSkg5TUNnc0hBN1hqMmI4WlB2d0o4OHZNY041ZC9JQlgvCi9Eb2lObzdXbEswVGN3YkpUY1JaYloyTS9rODJnNW5CcFJJVlRaWHl5Vm1CSWNkTE9paHd6ZFFMeGpyTVFmcjMKdGlxdjR3cS9YeFNmSjNIdHJPZ0xmNkdTYklPckhMN1poa0x2UWhuamxTM1QvOUpRazhCSVpmbHFCRFZVZ3JYZAo0K09uVHkzdTlrd0dSdkgxUnBOSThtWDh6RXBuQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUQ1hKUG5xK2duYVVVMHo4dWR1MUxnV2MrRFJ6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0tyenl1NHRNQwpZN1JSWDkrVGF5WEM4UDhSdnNCdmhEQlBWWmNoVm0rVlVYV2JqT2Nhc1pWL3lxMGJUc1JzeUFkYkVEc3FrVjlXCkd1N3phc0R2c3diNURFSTQ2a2NoZlErQkRObzVTWk1oSnoxMStPenJ0dkpHMlNGQ3crQU4wM3NubURDbnQ1SGEKbWZPbmFGS1dRMWpFN0VnYUMxVndLbVBrNjBWQnBKZ2kzTTZHSEFEZ0Nma2oyT2EvNXk0bTNDcU9DU0dhSmNBdgpGYXVaREVUS1ZSNCtoS3hkT0FMd1ZhQTk1OVcvTk1yY3dXZFVqbWEyYTlpTGMxSHFaZlZydERYVFpmT1g3WU1HCklyUXhleG9WaUJqUC9pckI2QTNMUldhQmd4OXhqa2c5dXc4aW9NOVZXT0lUNlg2QVhHMUdCcnljaU9xUEdHb1YKWjlDUUZLT1pnZ1pMCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://2F1A8AEF82B4EBAF7E32878B6859E5A5.gr7.ap-south-1.eks.amazonaws.com
  name: arn:aws:eks:ap-south-1:713881821143:cluster/homework-eks
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWktVNXpRVjdaMmt3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBek1EWXdOakl6TXpOYUZ3MHpOVEF6TURRd05qSTRNek5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUQwSnhmK2oxeW9tNmYzdjJ3Yk5TdnY5SkpIN3lxdjF0ZXBIL0VRVDZEZjc1N0hIcWRrVUZkYjgvUDkKVWFDcWRvb2lOQXF1RWJlUXZnTTBWR3RvRy85bDQ0L1JPZVNhTitlUEI4bFc1WXZuVW1BZzVWVEpPak5pdzRlcgp5R0x5WUtLWElUaHBIWll3eUNLMzROQ2owdzVUdlBvYUhqTVJRM0IzclAxS2JjejRVSTMzQUhic3lPZGp5Nlk1Ck0veitSVDBqdnFnSjNJc25VOHI2WFFjMlZHa2JvbkROOW1FcTMvYk9OOVpLOFVaWklWamdBSkt6T3EwNFA0Z2oKZjhEUVQ5dDc5K1lhYk0yNjg5N0pYcmJxcFcySnVDWHY3ZU81UUJhSjBaK00ybjNGayt6K0EwYUJURlMvWm1zSApqZVg2N2VMeGxyMGRvWUJUL21OTnZ3ZTRkSW83QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSK0FKK1lIQWRHOHpBNzczZjZuY1A3ZjV4Zyt6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQzI0YnpuYlcwcQpjWURWUVp5Z1E2eFhVOHJIcnNRR0tyN056b1ZtaXI2RGk1WCthYy8vRUFSRzQ1VWlFdGRNanZtd24zdU8wY1ErCjlMeWF3KzJFc2xMdVlLQ08zeDh1VnErMmM1UkJQNGlzck5ZbkpyRkpvUnZZS2d2emlqcy9aeHdaMnQ2eS8yN1MKWHpzREM1ZHpPajkzN05ibUtSckxpMThaU0p4Z0tzQTJlVXR3NWYvRVJDU2cxRldDbnFiUktZaXllTys4WWxYSwpXVm5JeWlhMVVZRjlXSkpOZnFyelNmU1hNM3RxRUlOSTk1WTU5Q2FtTlAwbnYyUUhnbXhIcUFkWDFqb2JONFBNCjVNeFBvWlJ0OUROSUs5MURiYWU4MEd5UFdpemJBMUtqVGFLRVhndXRLUlRnU296eDFKZnZsc2htVDlXOXVVb1QKMGIrcTkzNFJxQzNYCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://F85B14198780DF5F59684367EAE46087.gr7.ap-south-1.eks.amazonaws.com
  name: arn:aws:eks:ap-south-1:713881821143:cluster/ted-search-cluster
- cluster:
    certificate-authority: /Users/misgavn/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sat, 15 Mar 2025 12:44:17 IST
        provider: minikube.sigs.k8s.io
        version: v1.35.0
      name: cluster_info
    server: https://127.0.0.1:62456
  name: minikube
contexts:
- context:
    cluster: arn:aws:eks:ap-south-1:713881821143:cluster/homework-eks
    user: arn:aws:eks:ap-south-1:713881821143:cluster/homework-eks
  name: arn:aws:eks:ap-south-1:713881821143:cluster/homework-eks
- context:
    cluster: arn:aws:eks:ap-south-1:713881821143:cluster/ted-search-cluster
    user: arn:aws:eks:ap-south-1:713881821143:cluster/ted-search-cluster
  name: arn:aws:eks:ap-south-1:713881821143:cluster/ted-search-cluster
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sat, 15 Mar 2025 12:44:17 IST
        provider: minikube.sigs.k8s.io
        version: v1.35.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: arn:aws:eks:ap-south-1:713881821143:cluster/homework-eks
kind: Config
preferences: {}
users:
- name: arn:aws:eks:ap-south-1:713881821143:cluster/DEV-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-south-1
      - eks
      - get-token
      - --cluster-name
      - DEV-cluster
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: arn:aws:eks:ap-south-1:713881821143:cluster/homework-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-south-1
      - eks
      - get-token
      - --cluster-name
      - homework-eks
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: arn:aws:eks:ap-south-1:713881821143:cluster/ted-search-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-south-1
      - eks
      - get-token
      - --cluster-name
      - ted-search-cluster
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: minikube
  user:
    client-certificate: /Users/misgavn/.minikube/profiles/minikube/client.crt
    client-key: /Users/misgavn/.minikube/profiles/minikube/client.key