name: Production Release and Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write 
  id-token: write  

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.check_release.outputs.new_version }}
      release_created: ${{ steps.check_release.outputs.release_created }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install semantic-release and plugins
        run: |
          npm install --no-save \
            semantic-release@20.1.3 \
            @semantic-release/git@10.0.1 \
            @semantic-release/changelog@6.0.3 \
            @semantic-release/npm@9.0.2 \
            @semantic-release/github@8.1.0 \
            @semantic-release/commit-analyzer@9.0.2 \
            @semantic-release/release-notes-generator@10.0.3

      - name: Create .releaserc file
        run: |
          cat > .releaserc << 'EOL'
          {
            "branches": ["main"],
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/changelog",
              ["@semantic-release/npm", {
                "npmPublish": false
              }],
              ["@semantic-release/github", {
                "assets": []
              }],
              ["@semantic-release/git", {
                "assets": ["package.json", "CHANGELOG.md"],
                "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
              }]
            ]
          }
          EOL

    #   - name: Semantic Release
    #     id: semantic
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    #     run: npx semantic-release

    #   - name: Check if release was created
    #     id: check_release
    #     run: |
    #       if [ -n "${{ steps.semantic.outputs.new_release_version }}" ]; then
    #         echo "New release version: ${{ steps.semantic.outputs.new_release_version }}"
    #         echo "release_created=true" >> $GITHUB_OUTPUT
    #         echo "new_version=${{ steps.semantic.outputs.new_release_version }}" >> $GITHUB_OUTPUT
    #       else
    #         echo "No new release was created"
    #         echo "release_created=false" >> $GITHUB_OUTPUT
    #       fi

      - name: Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Run semantic-release and capture its output
          npx semantic-release > semantic-output.txt
          
          # Check if a new release was published
          if grep -q "The next release version is" semantic-output.txt; then
            # Extract the version number
            VERSION=$(grep -o "The next release version is [0-9]\+\.[0-9]\+\.[0-9]\+" semantic-output.txt | grep -o "[0-9]\+\.[0-9]\+\.[0-9]\+")
            echo "new_release_version=$VERSION" >> $GITHUB_OUTPUT
            echo "new_release_published=true" >> $GITHUB_OUTPUT
            echo "Published new release: $VERSION"
          else
            echo "No new release was published"
            echo "new_release_published=false" >> $GITHUB_OUTPUT
          fi
        
      - name: Check if release was created
        id: check_release
        run: |
          if [ "${{ steps.semantic.outputs.new_release_published }}" == "true" ]; then
            echo "New release version: ${{ steps.semantic.outputs.new_release_version }}"
            echo "release_created=true" >> $GITHUB_OUTPUT
            echo "new_version=${{ steps.semantic.outputs.new_release_version }}" >> $GITHUB_OUTPUT
          else
            echo "No new release was created"
            echo "release_created=false" >> $GITHUB_OUTPUT
          fi
      - name: Debug Outputs
        run: |
          echo "semantic.outputs.new_release_version: ${{ steps.semantic.outputs.new_release_version }}"
          echo "semantic.outputs.new_release_published: ${{ steps.semantic.outputs.new_release_published }}"
          echo "check_release.outputs.release_created: ${{ steps.check_release.outputs.release_created }}"
          echo "check_release.outputs.new_version: ${{ steps.check_release.outputs.new_version }}"

  deploy:
    needs: release
    if: needs.release.outputs.release_created == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: hw-app:${{ needs.release.outputs.new_version }}
          outputs: type=docker, dest=/tmp/hw-app.tar

      - name: Load image
        run: docker load -i /tmp/hw-app.tar
      
      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: hw-app:${{ needs.release.outputs.new_version }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::713881821143:role/GithubActionRole
          aws-region: ap-south-1
      
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push image to ECR
        env:
          ECR_REGISTRY: 713881821143.dkr.ecr.ap-south-1.amazonaws.com
          ECR_REPOSITORY: prd/hw-app
          IMAGE_TAG: ${{ needs.release.outputs.new_version }}
        run: |
          docker tag hw-app:${{ needs.release.outputs.new_version }} $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag hw-app:${{ needs.release.outputs.new_version }} $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "Pushed image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          
      - name: Update GitOps Repo
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          VERSION: ${{ needs.release.outputs.new_version }}
        run: |
          git config --global credential.helper '!f() { echo username=x-access-token; echo password=${{ secrets.PAT_TOKEN }}; }; f'
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/misgav777/hw-k8s-config.git gitops
          cd gitops

          # Update the image tag in the values.yaml file
          sed -i 's|tag:.*|tag: "${{ needs.release.outputs.new_version }}"|g' environments/prd/values.yaml
          
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add environments/prd/values.yaml
          git commit -m "Promote hw-app ${{ needs.release.outputs.new_version }} to production"
          git push
          
          echo "ArgoCD will automatically deploy the changes to production environment"